export const products = [
  {
    id: 1,
    name: 'Sword',
    price: 100,
    category: 'weapon',
    inStock: true,
    quantity: 5,
  },
  {
    id: 2,
    name: 'Shield',
    price: 80,
    category: 'armor',
    inStock: true,
    quantity: 3,
  },
  {
    id: 3,
    name: 'Potion',
    price: 20,
    category: 'consumable',
    inStock: false,
    quantity: 0,
  },
  {
    id: 4,
    name: 'Armor',
    price: 150,
    category: 'armor',
    inStock: true,
    quantity: 2,
  },
  {
    id: 5,
    name: 'Bow',
    price: 90,
    category: 'weapon',
    inStock: false,
    quantity: 0,
  },
  {
    id: 6,
    name: 'Arrow',
    price: 5,
    category: 'ammo',
    inStock: true,
    quantity: 50,
  },
  {
    id: 7,
    name: 'Helmet',
    price: 70,
    category: 'armor',
    inStock: true,
    quantity: 4,
  },
  {
    id: 8,
    name: 'Boots',
    price: 40,
    category: 'armor',
    inStock: true,
    quantity: 6,
  },
  {
    id: 9,
    name: 'Ring',
    price: 200,
    category: 'accessory',
    inStock: false,
    quantity: 0,
  },
  {
    id: 10,
    name: 'Amulet',
    price: 120,
    category: 'accessory',
    inStock: true,
    quantity: 1,
  },
];
